import * as Charts from 'recharts';

const Recharts = {
  Area: Charts.Area,
  AreaChart: Charts.AreaChart,
  Bar: Charts.Bar,
  BarChart: Charts.BarChart,
  Brush: Charts.Brush,
  CartesianAxis: Charts.CartesianAxis,
  CartesianGrid: Charts.CartesianGrid,
  Cell: Charts.Cell,
  ComposedChart: Charts.ComposedChart,
  Cross: Charts.Cross,
  Curve: Charts.Curve,
  Customized: Charts.Customized,
  Dot: Charts.Dot,
  ErrorBar: Charts.ErrorBar,
  Funnel: Charts.Funnel,
  FunnelChart: Charts.FunnelChart,
  Global: Charts.Global,
  Label: Charts.Label,
  LabelList: Charts.LabelList,
  Layer: Charts.Layer,
  Legend: Charts.Legend,
  Line: Charts.Line,
  LineChart: Charts.LineChart,
  Pie: Charts.Pie,
  PieChart: Charts.PieChart,
  PolarAngleAxis: Charts.PolarAngleAxis,
  PolarGrid: Charts.PolarGrid,
  PolarRadiusAxis: Charts.PolarRadiusAxis,
  Polygon: Charts.Polygon,
  Radar: Charts.Radar,
  RadarChart: Charts.RadarChart,
  RadialBar: Charts.RadialBar,
  RadialBarChart: Charts.RadialBarChart,
  Rectangle: Charts.Rectangle,
  ReferenceArea: Charts.ReferenceArea,
  ReferenceDot: Charts.ReferenceDot,
  ReferenceLine: Charts.ReferenceLine,
  ResponsiveContainer: Charts.ResponsiveContainer,
  Sankey: Charts.Sankey,
  Scatter: Charts.Scatter,
  ScatterChart: Charts.ScatterChart,
  Sector: Charts.Sector,
  Surface: Charts.Surface,
  Symbols: Charts.Symbols,
  Text: Charts.Text,
  Tooltip: Charts.Tooltip,
  Trapezoid: Charts.Trapezoid,
  Treemap: Charts.Treemap,
  XAxis: Charts.XAxis,
  YAxis: Charts.YAxis,
  ZAxis: Charts.ZAxis,
};

export { Recharts };
